In [103]:
import os
import numpy as np
import matplotlib.pyplot as plt

In [104]:
ar = np.array([1,2,-3,6,7,-10,88,43,-98,17,39,45])
ar

array([  1,   2,  -3,   6,   7, -10,  88,  43, -98,  17,  39,  45])

In [105]:
#doklej do wektora ar wartości [4,5,9,10,23,-14,55,13]
ar = np.append(ar,[4,5,9,10,23,-14,55,13])

In [106]:
ar

array([  1,   2,  -3,   6,   7, -10,  88,  43, -98,  17,  39,  45,   4,
         5,   9,  10,  23, -14,  55,  13])

In [107]:
#znajdz index dla wartości 9 - użyj odpowiedniej funkcji
[4,5,9,10,23,-14,55,13].index(9)

2

In [108]:
#znajdź indeksy dla wartości mniejszych od zera - użyj odpowiedniej funkcji
np.where(ar < 0 )

(array([ 2,  5,  8, 17], dtype=int64),)

In [109]:
#wyświetl wartości mniejsze od zera
print ([int for int in ar if int < 0])


[-3, -10, -98, -14]


In [110]:
#policz średnią, zaokrąglij do jednego miejsca po przecinku
np.round(np.average(ar),2)

12.1

In [111]:
#stwórz zmienną ar_abs, wektor wartości bezwględnych z wektora ar
ar_abs = np.abs(ar)

In [112]:
ar_abs

array([ 1,  2,  3,  6,  7, 10, 88, 43, 98, 17, 39, 45,  4,  5,  9, 10, 23,
       14, 55, 13])

In [122]:
#stwórz zmienną ar_p, wektor pierwiastków trzeciego stopnia z wektora ar_abs
np.cbrt(ar_abs)

array([ 1.        ,  1.25992105,  1.44224957,  1.81712059,  1.91293118,
        2.15443469,  4.44796018,  3.50339806,  4.61043629,  2.57128159,
        3.39121144,  3.5568933 ,  1.58740105,  1.70997595,  2.08008382,
        2.15443469,  2.84386698,  2.41014226,  3.80295246,  2.35133469])

In [123]:
ar_p

array([ 1.        ,  1.25992105,  1.44224957,  1.81712059,  1.91293118,
        2.15443469,  4.44796018,  3.50339806,  4.61043629,  2.57128159,
        3.39121144,  3.5568933 ,  1.58740105,  1.70997595,  2.08008382,
        2.15443469,  2.84386698,  2.41014226,  3.80295246,  2.35133469])

In [128]:
#zaokrąglij wektor ar_p do dwóch miejsc po przecinku
ar_p = np.round(ar_p,2)

In [129]:
ar_p

array([ 1.  ,  1.26,  1.44,  1.82,  1.91,  2.15,  4.45,  3.5 ,  4.61,
        2.57,  3.39,  3.56,  1.59,  1.71,  2.08,  2.15,  2.84,  2.41,
        3.8 ,  2.35])

In [131]:
#zsumuj zaokrąglony wektor ar_p i podnieś go do kwadratu, 
#zmienną nazwij ar_sq, zmień typ tej zmiennej na liczbę całkowitą
ar_sq = np.square(np.sum(ar_p))

In [132]:
ar_sq

2559.3480999999997

In [133]:
ar_sq=int(ar_sq)

In [134]:
ar_sq

2559